<a href="https://colab.research.google.com/github/hesnacaliskan/Feed_Forward/blob/main/Feed_Forward.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
# convert input matrix to tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6]],dtype=torch.float).reshape(2,3)
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
# set seed for reproducibility
torch.manual_seed(1)

In [ ]:
# define weight matrices for hidden and output layers
hidden_weights = torch.randn(3,50,dtype=torch.float)
output_weights = torch.randn(50,1,dtype=torch.float)

hidden_weights, output_weights

(tensor([[-1.7205, -1.5835,  1.2246, -0.1596, -0.8170, -0.1687, -0.9185, -0.8003,
          -0.8991, -0.0879,  1.3134, -0.4186, -0.0860, -0.1424, -1.3107,  0.6717,
          -1.9505, -0.1363, -0.3901, -2.1097,  1.2281,  1.2387,  0.6899,  1.9605,
          -1.0363, -0.7959, -0.6600, -1.6467,  0.8895, -2.2541,  0.5738, -1.5809,
          -0.6021, -1.0709, -0.2293,  0.8809, -0.7319, -0.6784, -1.5085,  0.7940,
          -2.2473, -0.9960, -0.1543, -0.0902, -0.8172,  0.3023, -0.6743, -0.5118,
          -1.0335, -0.9282],
         [-0.8576,  1.1873,  0.8635, -1.0986, -0.2726,  0.5510,  0.8867, -0.7213,
          -0.1691, -0.1944, -0.1577, -0.0760, -0.1513,  1.1517,  1.0710, -0.2714,
          -1.4376,  0.9728,  0.2998,  1.4520, -0.4635, -0.0817,  0.9699,  0.6033,
          -2.1825, -1.2291,  0.1631, -0.5153,  0.3369,  1.1439, -0.1316, -2.3585,
          -0.4579, -0.4495,  2.1441,  0.8606, -0.8810,  0.3252,  0.1557,  0.3533,
          -0.9943,  1.7019, -0.1366, -0.1180,  0.4348,  0.6072,  0.07

In [ ]:
# define bias vectors for hidden and output layers
hidden_bias = torch.randn(1,50,dtype=torch.float)
output_bias = torch.randn(1,1,dtype=torch.float)

hidden_bias, output_bias

(tensor([[ 0.6134, -0.3264,  0.4251,  1.0518,  1.6644,  1.3884,  1.2475,  0.2022,
           0.5733, -0.0521,  0.7053,  0.3222,  0.7071,  1.2908,  0.8470,  2.4917,
           0.1673,  0.6795, -0.4589, -1.4555, -0.5053,  0.0417, -0.0381,  0.4068,
           0.8519, -0.1752,  0.4421,  0.4145, -0.6395,  0.3661,  0.6539, -0.7537,
           0.6950, -0.0925,  0.4207,  0.0655, -0.8982,  0.5760, -0.6045,  1.1574,
          -1.3785,  1.1119, -0.1948,  0.9820,  0.1731, -0.4572,  0.7908,  0.7415,
           1.0753, -0.0854]]),
 tensor([[-1.1910]]))

In [ ]:
def tanh(x):
    return (torch.exp(x) - torch.exp(-x)) / (torch.exp(x) + torch.exp(-x))

In [ ]:
def sigmoid(x):
    return 1 / (1 + torch.exp(-x))

In [ ]:
# forward propagation
hidden_layer_output = tanh(torch.matmul(x, hidden_weights) + hidden_bias)
output_layer_output = sigmoid(torch.matmul(hidden_layer_output, output_weights) + output_bias)


In [ ]:
hidden_layer_output

tensor([[ 1.0000, -0.9999, -0.9715,  0.8398,  1.0000,  0.9976,  0.6553,  0.0966,
         -1.0000, -0.9884, -0.9945, -0.9999, -0.9988, -0.9252,  0.9997,  0.8464,
         -0.8107, -0.9013, -0.4241, -0.9594,  1.0000,  0.7793, -0.9511,  1.0000,
         -1.0000,  0.9043, -0.9847, -0.8364,  0.9900, -1.0000,  0.4649,  0.9986,
         -0.8771, -0.9977, -0.9976, -1.0000,  0.9950, -0.8740, -0.0797, -0.1578,
         -0.9808, -0.9070, -0.9998,  1.0000,  0.9997, -0.7741,  0.9774,  0.9788,
          0.9989, -0.9939],
        [ 0.9999, -1.0000, -0.9998,  0.7828,  1.0000,  1.0000, -0.9676, -0.9826,
         -1.0000, -1.0000, -0.9999, -1.0000, -1.0000, -0.4520,  1.0000,  0.9659,
         -0.9997, -1.0000,  0.9895, -0.9902,  1.0000,  0.8033, -1.0000,  1.0000,
         -1.0000,  0.9991, -1.0000, -1.0000,  1.0000, -1.0000, -0.9819,  1.0000,
          0.8862, -1.0000, -1.0000, -1.0000,  1.0000, -0.9941,  0.6409, -0.9781,
         -1.0000, -0.3354, -1.0000,  1.0000,  1.0000, -0.8837,  1.0000,  0.9788,


In [ ]:
torch.tanh(torch.matmul(x, hidden_weights) + hidden_bias)

tensor([[ 1.0000, -0.9999, -0.9715,  0.8398,  1.0000,  0.9976,  0.6553,  0.0966,
         -1.0000, -0.9884, -0.9945, -0.9999, -0.9988, -0.9252,  0.9997,  0.8464,
         -0.8107, -0.9013, -0.4241, -0.9594,  1.0000,  0.7793, -0.9511,  1.0000,
         -1.0000,  0.9043, -0.9847, -0.8364,  0.9900, -1.0000,  0.4649,  0.9986,
         -0.8771, -0.9977, -0.9976, -1.0000,  0.9950, -0.8740, -0.0797, -0.1578,
         -0.9808, -0.9070, -0.9998,  1.0000,  0.9997, -0.7741,  0.9774,  0.9788,
          0.9989, -0.9939],
        [ 0.9999, -1.0000, -0.9998,  0.7828,  1.0000,  1.0000, -0.9676, -0.9826,
         -1.0000, -1.0000, -0.9999, -1.0000, -1.0000, -0.4520,  1.0000,  0.9659,
         -0.9997, -1.0000,  0.9895, -0.9902,  1.0000,  0.8033, -1.0000,  1.0000,
         -1.0000,  0.9991, -1.0000, -1.0000,  1.0000, -1.0000, -0.9819,  1.0000,
          0.8862, -1.0000, -1.0000, -1.0000,  1.0000, -0.9941,  0.6409, -0.9781,
         -1.0000, -0.3354, -1.0000,  1.0000,  1.0000, -0.8837,  1.0000,  0.9788,


In [ ]:
output_layer_output

tensor([[0.9998],
        [0.9984]])

In [ ]:
torch.sigmoid(torch.matmul(hidden_layer_output, output_weights) + output_bias)


tensor([[0.9998],
        [0.9984]])

In [ ]:
torch.manual_seed(190401007)

In [ ]:
hidden_weights = torch.randn(3, 50, dtype=torch.float)
output_weights = torch.randn(50, 1, dtype=torch.float)

hidden_bias = torch.randn(1,50, dtype=torch.float)
output_bias = torch.randn(1,1, dtype=torch.float)


def tanh(x):
    return (torch.exp(x) - torch.exp(-x)) / (torch.exp(x) + torch.exp(-x))

def sigmoid(x):
    return 1 / (1 + torch.exp(-x))


hidden_layer_output = tanh(torch.matmul(x, hidden_weights) + hidden_bias)
output_layer_output = sigmoid(torch.matmul(hidden_layer_output, output_weights) + output_bias)

print(output_layer_output)


tensor([[0.0070],
        [0.0009]])
