<a href="https://colab.research.google.com/github/hesnacaliskan/Feed_Forward/blob/main/Feed_Forward.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
import torch

In [62]:
# convert input matrix to tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6]],dtype=torch.float)
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [63]:
x = torch.flatten(x)

In [64]:
# set seed for reproducibility
torch.manual_seed(1)

In [65]:
# define weight matrices for hidden and output layers
hidden_weights = torch.randn(6,50,dtype=torch.float)
output_weights = torch.randn(50,1,dtype=torch.float)

hidden_weights, output_weights

(tensor([[-1.5256e+00, -7.5023e-01, -6.5398e-01, -1.6095e+00, -1.0017e-01,
          -6.0919e-01, -9.7977e-01, -1.6091e+00, -7.1214e-01,  3.0372e-01,
          -7.7731e-01, -2.5146e-01, -2.2227e-01,  1.6871e+00,  2.2843e-01,
           4.6764e-01, -6.9697e-01, -1.1608e+00,  6.9954e-01,  1.9908e-01,
           8.6569e-01,  2.4440e-01, -6.6291e-01,  8.0731e-01,  1.1017e+00,
          -1.7594e-01, -2.2456e+00, -1.4465e+00,  6.1155e-02, -6.1774e-01,
          -7.9807e-01, -1.3162e-01,  1.8793e+00, -7.2132e-02,  1.5777e-01,
          -7.7345e-01,  1.9906e-01,  4.5703e-02,  1.5296e-01, -4.7568e-01,
          -1.1102e-01,  2.9274e-01, -1.5785e-01, -2.8787e-02,  2.3571e+00,
          -1.0373e+00,  1.5748e+00, -6.2985e-01, -9.2739e-01,  5.4514e-01],
         [ 6.6280e-02, -4.3704e-01,  7.6260e-01,  4.4151e-01,  1.1651e+00,
           2.0154e+00,  1.3741e-01,  9.3864e-01, -1.8600e-01, -6.4464e-01,
           1.5392e+00, -8.6959e-01, -3.3312e+00, -7.4787e-01, -2.5502e-02,
          -1.0233e+00, -

In [66]:
# define bias vectors for hidden and output layers
hidden_bias = torch.randn(1,50,dtype=torch.float)
output_bias = torch.randn(1,1,dtype=torch.float)

hidden_bias, output_bias

(tensor([[-1.7949,  0.7299, -0.5619, -0.1579,  1.5043, -1.3950,  0.8008, -0.6619,
          -1.0592, -0.6280, -0.2713,  1.8469, -0.0312, -0.0939, -0.6191, -0.6363,
           0.1383,  1.0735,  0.4096, -1.5421, -1.0129, -0.0297, -0.2890,  0.1522,
           2.4291,  1.3981, -0.6281,  1.1969,  0.6110, -0.4548, -0.9604,  0.2769,
          -1.2548,  1.3883,  0.9385,  1.4253,  1.5083,  0.1054, -1.6050, -0.1064,
           0.2466,  0.6125,  0.7398, -0.1786,  0.0785, -0.4398, -0.3608, -1.2617,
           1.9147, -1.8613]]),
 tensor([[0.9042]]))

In [67]:
def tanh(x):
    return (torch.exp(x) - torch.exp(-x)) / (torch.exp(x) + torch.exp(-x))

In [68]:
def sigmoid(x):
    return 1 / (1 + torch.exp(-x))

In [69]:
# forward propagation
hidden_layer_output = tanh(torch.matmul(x, hidden_weights) + hidden_bias)
output_layer_output = sigmoid(torch.matmul(hidden_layer_output, output_weights) + output_bias)


In [70]:
hidden_layer_output

tensor([[-0.9947,  0.7653, -1.0000, -0.9124,  0.4955,  1.0000,  0.9937,  1.0000,
         -1.0000,  1.0000,  1.0000,  1.0000, -1.0000, -0.9994,  0.9907,  1.0000,
         -1.0000,  1.0000,  1.0000,  1.0000,  1.0000, -1.0000, -0.9977,  0.9997,
          1.0000, -0.4574, -0.9901, -0.9958,  1.0000,  1.0000,  0.8839, -0.9999,
         -0.9998, -1.0000,  1.0000, -1.0000, -0.4880, -1.0000,  0.9917,  0.9997,
          1.0000,  1.0000,  0.9999, -1.0000,  1.0000,  0.9515,  1.0000, -0.1720,
         -1.0000, -1.0000]])

In [71]:
torch.tanh(torch.matmul(x, hidden_weights) + hidden_bias)

tensor([[-0.9947,  0.7653, -1.0000, -0.9124,  0.4955,  1.0000,  0.9937,  1.0000,
         -1.0000,  1.0000,  1.0000,  1.0000, -1.0000, -0.9994,  0.9907,  1.0000,
         -1.0000,  1.0000,  1.0000,  1.0000,  1.0000, -1.0000, -0.9977,  0.9997,
          1.0000, -0.4574, -0.9901, -0.9958,  1.0000,  1.0000,  0.8839, -0.9999,
         -0.9998, -1.0000,  1.0000, -1.0000, -0.4880, -1.0000,  0.9917,  0.9997,
          1.0000,  1.0000,  0.9999, -1.0000,  1.0000,  0.9515,  1.0000, -0.1720,
         -1.0000, -1.0000]])

In [72]:
output_layer_output

tensor([[0.9729]])

In [73]:
torch.sigmoid(torch.matmul(hidden_layer_output, output_weights) + output_bias)


tensor([[0.9729]])

We replace the SEED value with our student number.

In [51]:
torch.manual_seed(190401007)

In [59]:
hidden_weights = torch.randn(6, 50, dtype=torch.float)
output_weights = torch.randn(50, 1, dtype=torch.float)

hidden_bias = torch.randn(1,50, dtype=torch.float)
output_bias = torch.randn(1,1, dtype=torch.float)


def tanh(x):
    return (torch.exp(x) - torch.exp(-x)) / (torch.exp(x) + torch.exp(-x))

def sigmoid(x):
    return 1 / (1 + torch.exp(-x))


hidden_layer_output = tanh(torch.matmul(x, hidden_weights) + hidden_bias)
output_layer_output = sigmoid(torch.matmul(hidden_layer_output, output_weights) + output_bias)

print(output_layer_output)


tensor([[0.9886]])
